### ISSUE TITLE
Improve fault tolerance in EBS snapshot utilities

### ISSUE THREAD

**Issue by bharanin** [CU-CloudCollab/cucloud_ruby#28]
ec2.backup_volumes_unless_recent_backup() should attempt to complete all backups - failures should be batched into a single exception after all volumes are processed, rather than raising after first encountered error.

Lower-level ec2. create_ebs_snapshot() might also benefit from a retry block with a parameter for maximum retries.

**Comment by paul-e-allen** [comment]
More support for this issue:

```
/usr/local/bundle/gems/aws-sdk-core-2.6.35/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': The volume 'vol-0240c504b181eb49d' is 'retired' (Aws::EC2::Errors::IncorrectState)
	from /usr/local/bundle/gems/aws-sdk-core-2.6.35/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.6.35/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.6.35/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-2.6.35/lib/seahorse/client/request.rb:70:in `send_request'
	from /usr/local/bundle/gems/aws-sdk-core-2.6.35/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from /usr/local/bundle/gems/cucloud-0.7.7/lib/cucloud/ec2_utils.rb:169:in `create_ebs_snapshot'
	from /usr/local/bundle/gems/cucloud-0.7.7/lib/cucloud/ec2_utils.rb:209:in `block in backup_volumes_unless_recent_backup'
	from /usr/local/bundle/gems/cucloud-0.7.7/lib/cucloud/ec2_utils.rb:196:in `each'
	from /usr/local/bundle/gems/cucloud-0.7.7/lib/cucloud/ec2_utils.rb:196:in `backup_volumes_unless_recent_backup'
	from bin/auto_snapshot.rb:49:in `<main>'
```
